import Head from "next/head";
import { useContext } from "react";
import { LocationContext } from "../AppContext";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { location } = useContext(LocationContext);
  console.log("location", location);
  return (
    <div className={styles.container}>
      <Head>
        <title>Geo Tags</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mt-40 mx-auto"></main>
    </div>
  );
}
